services:
  postgres:
    image: postgres:15
    container_name: cts-postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cts-internal

  backend:
    build:
      context: ./back/cts
      dockerfile: Dockerfile.prod
    container_name: cts-backend
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
    networks:
      - cts-internal

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    container_name: cts-frontend
    depends_on:
      - backend
    networks:
      - cts-internal
      - traefik-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      # Frontend routes
      - "traefik.http.routers.cts-frontend.rule=Host(`cuisinetasaison.fr`) || Host(`www.cuisinetasaison.fr`)"
      - "traefik.http.routers.cts-frontend.entrypoints=websecure"
      #- "traefik.http.routers.cts-frontend.tls=true"
      - "traefik.http.routers.cts-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.cts-frontend.loadbalancer.server.port=80"
      # HTTP to HTTPS redirect
      #- "traefik.http.routers.cts-frontend-http.rule=Host(`cuisinetasaison.fr`)"
      #- "traefik.http.routers.cts-frontend-http.entrypoints=web"
      #- "traefik.http.routers.cts-frontend-http.middlewares=https-redirect"
      #- "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      # Redirection www vers non-www (optionnel)
      - "traefik.http.middlewares.redirect-www.redirectregex.regex=^https://www\\.cuisinetasaison\\.fr/(.*)"
      - "traefik.http.middlewares.redirect-www.redirectregex.replacement=https://cuisinetasaison.fr/$${1}"
      - "traefik.http.middlewares.redirect-www.redirectregex.permanent=true"
volumes:
  postgres_data:

networks:
  cts-internal:
    driver: bridge
  traefik-network:
    external: true
